main: aliuly\spawnmgr\Main
api: 1.10.0
load: POSTWORLD

name: SpawnMgr
description: More spawn related settings
version: 1.1.0
author: aliuly

permissions:
    spawnmgr.receive.armor:
        default: true
        description: "allows to receive armor when you spawn"
    spawnmgr.receive.items:
        default: true
        description: "allows to receive items when you spawn"
    spawnmgr.keepinv:
        default: op
        description: "allow player to keep inventory"
    spawnmgr.spawnmode:
        default: true
        description: "player will follow spawn-control setting"
    spawnmgr.reserved:
        default: op
        description: "Players is allowed to join full servers"
